<form action="signup" method="POST">
    <fieldset>
        <legend>REGISTRARTE</legend>

        <div class="mb-3">
            <label for="usuario">Nombre de usuario:</label>
            <input class="form-control" type="usuario" name="usuario" required>
        </div>
        <div class="mb-3">
            <input type="hidden" name="action" value="signup/">
        </div>
        <div class="mb-3">
            <label for="contraseña">Contraseña:</label>
            <input class="form-control" type="password" name="password" required>
        </div>

        <button class="btn btn-success" type="submit">ENVIAR</button>
    </fieldset>
</form>
<div>
    <p><?php echo $error ?></p>
</div>