<!DOCTYPE html>
<html lang="es">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    </head>
<body>
    <header>
        <h1>TIENDA ONLINE</h1>
        <div>
            <a class='btn btn-danger'  href='?action=logout/'>Cerrar Sesion</a>
             <a class='btn btn-primary'  href='?action=login/'>Iniciar Sesion</a>
             <a class='btn btn-success' href='?action=signup/'>Registrarte</a>
        </div>
</header>