<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Género</th>
            <th>Consola</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php
        echo "<tr>";
        echo "<th> " . $juego->id . "</th>";
        echo "<th> " . $juego->nombre . "</th>";
        echo "<th>" . $juego->genero . "</th>";
        foreach ($consolas as $consola) {
            if ($consola->id == $juego->id_consola) {
                echo "<th>" . $consola->nombre . "</th>";

            }
        }

    
        echo "<td><a  class='btn btn-danger' href='?action=eliminar/" . $juego->id . "'>Eliminar</a></td>";
        echo "<td><a class='btn btn-primary'  href='?action=editar/" . $juego->id . "'>Editar</a></td>";


        echo "</tr>";
        ?>

    </tbody>

</table>